# Generated by Django 5.0.4 on 2024-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
