# Generated by Django 5.0.4 on 2024-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品詳細説明'),
        ),
    ]
